export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_SUCCESS_LOGIN = 'AUTH_SUCCESS_LOGIN';
export const AUTH_FAILED_LOGIN = 'AUTH_FAILED_LOGIN';
export const AUTH_VALID_TOKEN = 'AUTH_VALID_TOKEN';
export const AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN';

export const BOARD_REQUEST_BYID = 'BOARD_REQUEST_BYID';
export const BOARD_SUCCESS_BYID = 'BOARD_SUCCESS_BYID';
export const BOARD_FAILED_BYID = 'BOARD_FAILED_BYID';

export const LIST_GET_ALL = 'LIST_GET_ALL';
export const LIST_CREATE = 'LIST_CREATE';
export const LIST_UPDATE = 'LIST_UPDATE';
export const LIST_ITEM_PREVIEW = 'LIST_ITEM_PREVIEW';
export const LIST_ITEM_PREVIEW_ABORT = 'LIST_ITEM_PREVIEW_ABORT';

export const ACTIVITY_GET_ALL = 'ACTIVITY_GET_ALL';
export const ACTIVITY_UPDATE = 'ACTIVITY_UPDATE';
export const ACTIVITY_CREATE = 'ACTIVITY_CREATE';